import type { Metadata } from "next";
import Header from './components/header'
import Client from './components/client'
import Footer from './components/footer'
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="">
          <Client></Client>
          <Header></Header>
          {children}
          <Footer></Footer>
        </div>
      </body>
        
    </html>
  );
}
